baseurl = "/"
title = "Lintel"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Lintel.US"
    description = "Technews You Can Use"
#    github = "https://github.com/XXX"
#    twitter = "https://twitter.com/XXX"
    email = "peter.lists+lintel@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
